/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

/* Address of Registers */
// SCU Registers
#define SCU_BASE        (0xF0036000)
#define SCU_WDT_CPU0CON0 (*(volatile unsigned int*)(SCU_BASE + 0x100))
#define SCU_WDTSCON0  (*(volatile unsigned int*)(SCU_BASE + 0x0F0))
#define SCU_EICR1     (*(volatile unsigned int*)(SCU_BASE + 0x214))// ERS2, 3
#define SCU_IGCR0     (*(volatile unsigned int*)(SCU_BASE + 0x22C))


#define LCK             1
#define ENDINIT         0
#define INP0          12
#define INP1          28
#define EIEN0         11
#define EIEN1         27
#define FEN0          8
#define FEN1          24
#define EXIS0         4
#define EXIS1         20
#define IGP0          14
#define IGP1          30


// GTM Registers
// GTM - CMU
#define GTM_BASE                    (0xF0100000)
#define GTM_CMU_CLK_EN              (*(volatile unsigned int*)(GTM_BASE + 0x00300))
#define GTM_CMU_FXCLK_CTRL          (*(volatile unsigned int*)(GTM_BASE + 0x00344))

#define EN_FXCLK                    22
#define FXCLK_SEL                   0

// GTM - TOM0
#define GTM_TOM0_TGC1_GLB_CTRL      (*(volatile unsigned int*)(GTM_BASE + 0x08230))
#define GTM_TOM0_TGC1_ENDIS_CTRL    (*(volatile unsigned int*)(GTM_BASE + 0x08270))
#define GTM_TOM0_TGC1_OUTEN_CTRL    (*(volatile unsigned int*)(GTM_BASE + 0x08278))
#define GTM_TOM0_TGC1_FUPD_CTRL     (*(volatile unsigned int*)(GTM_BASE + 0x08238))
#define GTM_TOM0_CH11_CTRL          (*(volatile unsigned int*)(GTM_BASE + 0x082C0))
#define GTM_TOM0_CH11_SR0           (*(volatile unsigned int*)(GTM_BASE + 0x082C4))
#define GTM_TOM0_CH11_SR1           (*(volatile unsigned int*)(GTM_BASE + 0x082C8))

#define UPEN_CTRL3                  22
#define HOST_TRIG                   0
#define ENDIS_CTRL3                 6
#define OUTEN_CTRL3                 6
#define RSTCN0_CH3                  22
#define FUPD_CTRL3                  6
#define CLK_SRC_SR                  12
#define SL                          11

// GTM
#define GTM_CLC                     (*(volatile unsigned int*)(GTM_BASE + 0x9FD00))
#define GTM_TOUTSEL0                (*(volatile unsigned int*)(GTM_BASE + 0x9FD30))

#define DISS                        1
#define DISR                        0
#define SEL3                        6

// SRC Registers
#define SRC_BASE     (0xF0038000)
#define SRC_SCUERU0  (*(volatile unsigned int*)(SRC_BASE + 0xCD4))
#define SRC_SCUERU1  (*(volatile unsigned int*)(SRC_BASE + 0xCD8))

#define TOS          11
#define SRE          10
#define SRPN         0

// PORT02 Registers
#define PORT02_BASE     (0xF003A200)
#define PORT10_BASE    (0xF003B000)

#define PORT02_IOCR0   (*(volatile unsigned int*)(PORT02_BASE + 0x10))
#define PORT02_IOCR4   (*(volatile unsigned int*)(PORT02_BASE + 0x14))
#define PORT02_OMR     (*(volatile unsigned int*)(PORT02_BASE + 0x04))
#define PORT02_IN      (*(volatile unsigned int*)(PORT02_BASE + 0x24))


#define PORT10_IOCR0   (*(volatile unsigned int*)(PORT10_BASE + 0x10))
#define PORT10_IOCR4   (*(volatile unsigned int*)(PORT10_BASE + 0x14))
#define PORT10_OMR     (*(volatile unsigned int*)(PORT10_BASE + 0x04))



// SRC Registers
#define SRC_BASE     (0xF0038000)
#define SRC_SCUERU0  (*(volatile unsigned int*)(SRC_BASE + 0xCD4))
#define SRC_SCUERU1  (*(volatile unsigned int*)(SRC_BASE + 0xCD8))

#define TOS          11
#define SRE          10
#define SRPN         0

// IOCRX register offset
#define PC0      3
#define PC1     11
#define PC2     19
#define PC3     27
#define PC5     11
#define PC7     27

//단색 LED
#define PCL1   17
#define PCL2   18

#define PS1    1
#define PS2    2


#define P0     0
#define P1     1

/* Function Prototype */
void init_Buzzer(void);
void init_GTM_TOM0_PWM(void);
void init_LED(void);
void init_Switch(void);
void init_ERU(void);

IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define PWM_FREQ        6250000

//int num_tones = 8;
//int tones[] = {261, 277, 294, 311, 330, 349, 370, 392};
int num_tones = 1;
int tones[] = {261};

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    init_Buzzer();
    init_GTM_TOM0_PWM();
    init_LED();
    init_Switch();
    init_ERU();

    while(1)
    {
/*        for(int i = 0 ; i < num_tones ; i++)
        {
            int pwm_cnt = PWM_FREQ / tones[i];

            GTM_TOM0_CH11_SR0 = pwm_cnt;
            GTM_TOM0_CH11_SR1 = pwm_cnt / 2;

            for(int j = 0 ; j < 50000000 ; j++) ;
        }
    */
    }

    return (1);
}

__interrupt(0x0A) __vector_table(0)
void ERU_ISR_SW1(void)
{
    PORT10_OMR |= ((1<<PCL1) | (1<<PS1));




    int pwm_cnt = PWM_FREQ / 261;

    GTM_TOM0_CH11_SR0 = pwm_cnt;
    GTM_TOM0_CH11_SR1 = pwm_cnt / 2;

    for(int j = 0 ; j < 5000000 ; j++) ;
    GTM_TOM0_CH11_SR1 = 0;





}

__interrupt(0x0B) __vector_table(0)
void ERU_ISR_SW2(void)
{
    PORT10_OMR |= ((1<<PCL2) | (1<<PS2));


    int pwm_cnt = PWM_FREQ / 330;

    GTM_TOM0_CH11_SR0 = pwm_cnt;
    GTM_TOM0_CH11_SR1 = pwm_cnt / 2;

    for(int j = 0 ; j < 5000000 ; j++) ;
    GTM_TOM0_CH11_SR1 = 0;




}


// Initialize LED (RED&BLUE)
void init_LED(void)
{
    //Reset PC1 & PC2 in IOCR0
    PORT10_IOCR0 &= ~((0x1F) << PC1);
    PORT10_IOCR0 &= ~((0x1F) << PC2);

    //Set PC1 & PC2 with push pull(2b10000) : p.13-25 Table 13-5

    PORT10_IOCR0 |= ((0x10) << PC1);
    PORT10_IOCR0 |= ((0x10) << PC2);

}

//Initialize Switch
void init_Switch(void)
{
    //Set PC0 & PC1 pullup 저항(0XX10) : p.13-24 Table 13-5
    //PCx | 10000 --> 10h | Push-Pull | General-purpose output

    //SW
    PORT02_IOCR0  &= ~((0x1F) << PC0);
    PORT02_IOCR0  &= ~((0x1F) << PC1);

    PORT02_IOCR0  &= ~((0x2) << PC0);
    PORT02_IOCR0  &= ~((0x2) << PC1);

}


void init_Buzzer(void)
{
    PORT02_IOCR0 &= ~((0x1F) << PC3);           // PORT02.3 : Alternate output function 1 (push-pull)
    PORT02_IOCR0 |= ((0x11) << PC3);            // PORT02.3 : GTM_TOUT3

}


/* Initialize External Request Unit (ERU) */
void init_ERU(void)
{
    /* ERU Input Channel 2 Setting */
    /* Password Access to unlock WDTSCON0 */
    SCU_WDTSCON0 = ((SCU_WDTSCON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDTSCON0 & (1<< LCK)) !=0);

    // Modify Aceess to clear ENDINIT bit
    SCU_WDTSCON0 = ((SCU_WDTSCON0 ^ 0xFC) | (1 << LCK)) & ~ (1 << ENDINIT);
    while((SCU_WDTSCON0 &(1 << LCK))==0);

//SW1
    SCU_EICR1 &~ ~((0x7) << EXIS0);         // External input 1 selected
    SCU_EICR1 |=  ((0x1) << EXIS0);

    SCU_EICR1 |= (1<< FEN0);                // Falling edge enable

    SCU_EICR1 |=((0x1) << EIEN0);           // The trigger event is enabled

    SCU_EICR1 &= ~((0x7) << INP0);          // An event from input ETL 2 triggers output OGU 0

    SCU_IGCR0 &= ~((0x3) << IGP0);          // IOUT(0) is activated in response to a trigger event
    SCU_IGCR0 |= ((0x1) << IGP0);           // The pattern is not considered

//SW2
    SCU_EICR1 &~ ~((0x7) << EXIS1);         // External input 2 selected
    SCU_EICR1 |=  ((0x2) << EXIS1);

    SCU_EICR1 |= (1<< FEN1);                // Falling edge enable

    SCU_EICR1 |=((0x1) << EIEN1);           // The trigger event is enabled

    SCU_EICR1 &= ~((0x7) << INP1);          // An event from input ETL 2 triggers output OGU 1
    SCU_EICR1 |=((0x1) << INP1);           // The trigger event is enabled

    SCU_IGCR0 &= ~((0x3) << IGP1);          // IOUT(0) is activated in response to a trigger event
    SCU_IGCR0 |= ((0x1) << IGP1);           // The pattern is not considered


    /* Password Access to unlock WDTSCON0 */
    SCU_WDTSCON0 = ((SCU_WDTSCON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDTSCON0 & (1<< LCK)) !=0);

    // Modify Aceess to set ENDINIT bit
    SCU_WDTSCON0 = ((SCU_WDTSCON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDTSCON0 &(1 << LCK))==0);

    /* SRC Interrupt Setting for ECU */
    SRC_SCUERU0 &= ~((0xFF)<<SRPN);          // Set Priority : 0x0A
    SRC_SCUERU0 |= ((0x0A)<<SRPN);

    SRC_SCUERU0 &= ~((0x3) << TOS);          // CPU0 Services

    SRC_SCUERU0 |= (1<< SRE);                // Service Request is enabled


    SRC_SCUERU1 &= ~((0xFF)<<SRPN);          // Set Priority : 0x0B
    SRC_SCUERU1 |= ((0x0B)<<SRPN);

    SRC_SCUERU1 &= ~((0x3) << TOS);          // CPU0 Services

    SRC_SCUERU1 |= (1<< SRE);                // Service Request is enabled

}

void init_GTM_TOM0_PWM(void)
{
    /* GTM Enable */
    // Password Access to unlock WDTCPU0CON0
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    // Modify Access to clear ENDINIT bit
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);

    GTM_CLC &= ~(1 << DISR);                        // Enable GTM Module

    // Password Access to unlock WDTCPU0CON0
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    // Modify Access to set ENDINIT bit
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);

    while((GTM_CLC & (1 << DISS)) != 0);            // Wait until module is enabled

    /* GTM Clock Setting */
    GTM_CMU_FXCLK_CTRL &= ~((0xF) << FXCLK_SEL);    // Input clock of CMU_FXCLK : CMU_GCLK_EN

    GTM_CMU_CLK_EN &= ~((0x3) << EN_FXCLK);         // Enable all CMU_FXCLK
    GTM_CMU_CLK_EN |= ((0x2) << EN_FXCLK);

    /* GTM TOM0 PWM Setting */
    GTM_TOM0_TGC1_GLB_CTRL &= ~((0x3) << UPEN_CTRL3);   // TOM0 channel 11 enable update of
    GTM_TOM0_TGC1_GLB_CTRL |= ((0x2) << UPEN_CTRL3);    // register CM0, CM1, CLK_SRC

    GTM_TOM0_TGC1_FUPD_CTRL &= ~((0x3) << FUPD_CTRL3);  // Enable force update of TOM0 channel 11
    GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << FUPD_CTRL3);
    GTM_TOM0_TGC1_FUPD_CTRL &= ~((0x3) << RSTCN0_CH3);  // Reset CN0 of TOM0 channel 11 on force update
    GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << RSTCN0_CH3);

    GTM_TOM0_TGC1_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL3); // Enable channel 11 on an update trigger
    GTM_TOM0_TGC1_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL3);
    GTM_TOM0_TGC1_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL3); // Enable channel 11 output on an update trigger
    GTM_TOM0_TGC1_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL3);

    GTM_TOM0_CH11_CTRL |= (1 << SL);                    // High signal level for duty cycle

    GTM_TOM0_CH11_CTRL &= ~((0x7) << CLK_SRC_SR);       // Clock source : CMU_FXCLK(1) = 6250 kHz
    GTM_TOM0_CH11_CTRL |= (1 << CLK_SRC_SR);
    GTM_TOM0_CH11_SR0 = 12500 - 1;                      // PWM freq. = 6250 kHz / 12500 = 500 Hz
    GTM_TOM0_CH11_SR1 = 0;                              // Duty cycle = 0

    GTM_TOUTSEL0 &= ~((0x3) << SEL3);                   // TOUT3 : TOM0 channel 11

    GTM_TOM0_TGC1_GLB_CTRL |= (1 << HOST_TRIG);         // Trigger request signal to update
}
