/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

/* SCU Registers */
#define SCU_BASE            (0xF0036000)
#define SCU_WDT_CPU0CON0    (*(volatile unsigned int*)(SCU_BASE + 0x100))
#define LCK                 1
#define ENDINIT             0

// FOR LED
#define PORT10_BASE     (0xF003B000)
#define PORT10_IOCR0    (*(volatile unsigned int*)(PORT10_BASE + 0x10))     /* PORT10_IOCR0의 주소를 이용한 주소의 내용 (변수 아님) */
#define PORT10_OMR      (*(volatile unsigned int*)(PORT10_BASE + 0x04))     /* PORT10_OMR의 주소를 이용한 주소의 내용 (변수 아님)   */
/* volatile 타입으로 선언하는 이유는 동일한 메모리에 1/0을 반복적으로 쓰기를 하므로 컴파일러가 동일한 동작을 무의미하게 반복한다고 판단하여 '최적화'를 실행할 수 있으므로 이를 방지하기 위하여 'volatile' 형으로 선언함 */

#define P10_R0_PC1             11
#define P10_R0_PC2             19
#define P10_R0_PCL1            17
#define P10_R0_PCL2            18
#define P10_R0_PS1             1
#define P10_R0_PS2             2

// GTM
#define GTM_BASE                    (0xF0100000)

#define GTM_CLC                     (*(volatile unsigned int*)(GTM_BASE + 0x9FD00))
#define DISS                        1
#define DISR                        0

//GTM CMU 설정
#define GTM_CMU_FXCLK_CTRL          (*(volatile unsigned int*)(GTM_BASE + 0x00344))
#define FXCLK_SEL                   0
#define GTM_CMU_CLK_EN              (*(volatile unsigned int*)(GTM_BASE + 0x00300))
#define EN_FXCLK                    22

// GTM - TOM0 - TGC0 설정
#define GTM_TOM0_TGC0_GLB_CTRL      (*(volatile unsigned int*)(GTM_BASE + 0x08030))
#define HOST_TRIG                   0
#define UPEN_CTRL1                  18
#define UPEN_CTRL2                  20
#define GTM_TOM0_TGC0_FUPD_CTRL     (*(volatile unsigned int*)(GTM_BASE + 0x08038))   // TOM0 - TGC0 - 아래의 체널 1, 2에 트리거 신호가 업데이트 되도록 하기 위한 설정
#define RSTCN0_CH1                  18
#define FUPD_CTRL1                  2
#define RSTCN0_CH2                  20
#define FUPD_CTRL2                  4
#define GTM_TOM0_TGC0_ENDIS_CTRL    (*(volatile unsigned int*)(GTM_BASE + 0x08070))   // 트리거 신호에 따른 체널 1, 2의 enable
#define ENDIS_CTRL1                 2
#define ENDIS_CTRL2                 4
#define GTM_TOM0_TGC0_OUTEN_CTRL    (*(volatile unsigned int*)(GTM_BASE + 0x08078))   // 트리거 신호 발생 시, 체널 1,2의 아웃풋이 enable 되기 위한 설정
#define OUTEN_CTRL1                 2
#define OUTEN_CTRL2                 4

// GTM - TOM0 - Channel 1 설정        P10.1 (TOUT103, RED)
#define GTM_TOM0_CH1_CTRL           (*(volatile unsigned int*)(GTM_BASE + 0x08040))
#define SL                          11
#define CLK_SRC_SR                  12
#define GTM_TOM0_CH1_SR0            (*(volatile unsigned int*)(GTM_BASE + 0x08044))
#define GTM_TOM0_CH1_SR1            (*(volatile unsigned int*)(GTM_BASE + 0x08048))

// GTM - TOM0 - Channel 2 설정        P10.2 (TOUT104, BLUE)
#define GTM_TOM0_CH2_CTRL           (*(volatile unsigned int*)(GTM_BASE + 0x08080))
//#define SL                          11
//#define CLK_SRC_SR                  12
#define GTM_TOM0_CH2_SR0            (*(volatile unsigned int*)(GTM_BASE + 0x08084))
#define GTM_TOM0_CH2_SR1            (*(volatile unsigned int*)(GTM_BASE + 0x08088))

// TOUT 설정
#define GTM_TOUTSEL6                (*(volatile unsigned int*)(GTM_BASE + 0x9FD48))
#define SEL7                        14                                                 // TOUT103 (RED)
#define SEL8                        16                                                 // TOUT104 (BLUE)

/* VADC Registers */
#define VADC_BASE       (0xF0020000)
#define VADC_CLC        (*(volatile unsigned int*)(VADC_BASE + 0x000))                  // CLC register 설정 enable(DISR) 및 enable 확인(DISS)
#define DISS            1
#define DISR            0
#define VADC_G4ARBPR    (*(volatile unsigned int*)(VADC_BASE + 0x1484))                 // G4ARBPR register 설정
#define PRIO0           0
#define CSM0            3
#define ASEN0           24
#define VADC_G4QMR0     (*(volatile unsigned int*)(VADC_BASE + 0x1504))
#define ENGT            0
#define TREV            9
#define FLUSH           10
#define VADC_G4ARBCFG   (*(volatile unsigned int*)(VADC_BASE + 0x1480))
#define ANONC           0
#define VADC_G4ICLASS0  (*(volatile unsigned int*)(VADC_BASE + 0x14A0))
#define STCS            0
#define CMS             8
#define VADC_G4CHCTR7   (*(volatile unsigned int*)(VADC_BASE + 0x161C))
#define ICLSEL          0
#define RESREG          16
#define RESPOS          21
#define VADC_G4QINR0    (*(volatile unsigned int*)(VADC_BASE + 0x1510))
#define REQCHNR         0
#define RF              5
#define VADC_G4RES1     (*(volatile unsigned int*)(VADC_BASE + 0x1704))
#define RESULT          0
#define VF              31

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void init_GTM_TOM0_PWM(void);
void init_LED(void);
void unlock_Safety_Critical_Reg(void);
void lock_Safety_Critical_Reg(void);
void init_VADC(void);
void VADC_startConversion(void);
unsigned int VADC_readResult(void);

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    unsigned int adcResult;

    init_LED();
    init_GTM_TOM0_PWM();


    /* Initialization */
    init_VADC();                // Initialize VADC


    while(1)
    {
        VADC_startConversion();
        adcResult = VADC_readResult();

        GTM_TOM0_CH1_SR1 = 12500*(adcResult+1)/4096 - 1;       // ADC 출력값이 0~4095이므로 이값으로 그대로 연산하면 0이 곱해지며, 이때 -1항과의 연산에서 음수가 발생하므로, ADC 출력값을 0~4095 >> 1~4096으로 변경해서 연산함
        GTM_TOM0_CH2_SR1 = 12500*(adcResult+1)/4096 - 1;
    }

    return (1);
}

void init_GTM_TOM0_PWM(void)
{

    /* GTM Enable */
    unlock_Safety_Critical_Reg();
    GTM_CLC &= ~(1 << DISR);                        // Enable GTM Module
    lock_Safety_Critical_Reg();
    while((GTM_CLC & (1 << DISS)) != 0);            // Wait until module is enabled

    /* GTM Clock Setting */
    GTM_CMU_FXCLK_CTRL &= ~((0xF) << FXCLK_SEL);    // Input clock of CMU_FXCLK : select CMU_GCLK_EN (0000b)

    GTM_CMU_CLK_EN &= ~((0x3) << EN_FXCLK);         // Enable all CMU_FXCLK
    GTM_CMU_CLK_EN |= ((0x2) << EN_FXCLK);

    /* GTM TOM0 PWM Setting */
    GTM_TOM0_TGC0_GLB_CTRL &= ~((0x3) << UPEN_CTRL1);   // TOM0 channel 1 enable update of
    GTM_TOM0_TGC0_GLB_CTRL |= ((0x2) << UPEN_CTRL1);    // register CM0, CM1, CLK_SRC
    GTM_TOM0_TGC0_GLB_CTRL &= ~((0x3) << UPEN_CTRL2);   // TOM0 channel 2 enable update of
    GTM_TOM0_TGC0_GLB_CTRL |= ((0x2) << UPEN_CTRL2);    // register CM0, CM1, CLK_SRC

    GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << FUPD_CTRL1);  // Enable force update of TOM0 channel 1
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << FUPD_CTRL1);
    GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << FUPD_CTRL2);  // Enable force update of TOM0 channel 2
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << FUPD_CTRL2);
    GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << RSTCN0_CH1);  // Reset CN0 of TOM0 channel 1 on force update
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << RSTCN0_CH1);
    GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << RSTCN0_CH2);  // Reset CN0 of TOM0 channel 2 on force update
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << RSTCN0_CH2);

    GTM_TOM0_TGC0_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL1); // Enable channel 1 on an update trigger
    GTM_TOM0_TGC0_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL1);
    GTM_TOM0_TGC0_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL1); // Enable channel 1 output on an update trigger
    GTM_TOM0_TGC0_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL1);
    GTM_TOM0_TGC0_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL2); // Enable channel 2 on an update trigger
    GTM_TOM0_TGC0_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL2);
    GTM_TOM0_TGC0_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL2); // Enable channel 2 output on an update trigger
    GTM_TOM0_TGC0_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL2);

    GTM_TOM0_CH1_CTRL |= (1 << SL);                     // High signal level for duty cycle for CH.1
    GTM_TOM0_CH1_CTRL &= ~((0x7) << CLK_SRC_SR);        // Clock source : CMU_FXCLK(1) = 6250 kHz
    GTM_TOM0_CH1_CTRL |= (1 << CLK_SRC_SR);
    GTM_TOM0_CH2_CTRL |= (1 << SL);                     // High signal level for duty cycle for CH.2
    GTM_TOM0_CH2_CTRL &= ~((0x7) << CLK_SRC_SR);        // Clock source : CMU_FXCLK(1) = 6250 kHz
    GTM_TOM0_CH2_CTRL |= (1 << CLK_SRC_SR);

    GTM_TOM0_CH1_SR0 = 12500 - 1;                       // PWM freq. = 6250 kHz / 12500 = 500 Hz    for CH.1
    GTM_TOM0_CH2_SR0 = 12500 - 1;                       // PWM freq. = 6250 kHz / 12500 = 500 Hz    for CH.2
//    GTM_TOM0_CH1_SR1 = 0;                               // Duty cycle = 0
//    GTM_TOM0_CH1_SR1 = 3125-1;                               // Duty cycle = 25
//    GTM_TOM0_CH1_SR1 = 6250-1;                          // Duty cycle = 50
    GTM_TOM0_CH1_SR1 = 0;                       // for CH.1
    GTM_TOM0_CH2_SR1 = 0;                       // for CH.2

    GTM_TOUTSEL6 &= ~((0x3) << SEL7);                   // TOUT103 : TOM0 channel 1
    GTM_TOUTSEL6 &= ~((0x3) << SEL8);                   // TOUT103 : TOM0 channel 2

    GTM_TOM0_TGC0_GLB_CTRL |= (1 << HOST_TRIG);         // Trigger request signal to update
}

/* Initialize LED (RED & BLUE) */
void init_LED(void)
{
    /* reset PC1 & PC2 in IOCR0 */
    PORT10_IOCR0 &= ~((0x1F) << P10_R0_PC1);
    PORT10_IOCR0 &= ~((0x1F) << P10_R0_PC2);

    /* set PC1 & PC2 with push-pull (2b10000) */
    PORT10_IOCR0 |= ((0x11) << P10_R0_PC1);           // TOUT3 --> PC1 : 10011b로 설정 (3 포트)   red    PWM OUTPUT을 입력으로 받아서 LED 켜짐
    PORT10_IOCR0 |= ((0x11) << P10_R0_PC2);           // TOUT4 --> PC1 : 10100b로 설정 (4 포트)   blue   PWM OUTPUT을 입력으로 받아서 LED 켜짐
}

void init_VADC(void){
    /* VADC Enable */
    unlock_Safety_Critical_Reg();
    VADC_CLC &= ~(1 << DISR);                 // Enable VADC Module, DISR = 0
    lock_Safety_Critical_Reg();
    while((VADC_CLC & (1 << DISS)) != 0);     // Wait until module is enabled, DISS가 0 인지 재확인

    VADC_G4ARBPR |= ((0x3) << PRIO0);         // Highest Priority for Request Source 0,  011b를 입력
    VADC_G4ARBPR &= ~(1 << CSM0);             // Conversion Start Mode : Wait-for-start mode
    VADC_G4ARBPR |= (1 << ASEN0);             // Arbitration Source Input 0 Enable  1 입력

    VADC_G4QMR0  &= ~((0x3) << ENGT);         // Enable Conversion Requests
    VADC_G4QMR0  |= ((0x1) << ENGT);

    VADC_G4QMR0  |= (1 << FLUSH);             // Clear all Queue Entries

    VADC_G4ARBCFG |= ((0x3) << ANONC);        // Analog Converter : Normal Operation

    VADC_G4ICLASS0 &= ~((0x7) << CMS);        // Group-specific Class 0
                                              // Conversion Mode : Standard Conversion (12-bit)

    /* VADC Group 4 Channel 7 Setting */
    VADC_G4CHCTR7 |= (1 << RESPOS);           // Read Results Right-aligned
    VADC_G4CHCTR7 &= ~((0xF) << RESREG);      // Store Result in Group Result Register G4RES1
    VADC_G4CHCTR7 |= (1 << RESREG);
    VADC_G4CHCTR7 &= ~((0x3) << ICLSEL);      // Use Group-specific Class 0
}

void VADC_startConversion(void){
    /* No fill and Start Queue */
    VADC_G4QINR0 &= ~(0x1F);
    VADC_G4QINR0 |= (0x07);                  // Request Channel Number : 7

    VADC_G4QINR0 &= ~(1 << RF);              // No fill : it is converted once
//    VADC_G4QINR0 |= (1 << RF);               // automatic refill

    VADC_G4QMR0 |= (1 << TREV);              // Generate a Trigger Event
}

unsigned int VADC_readResult(void)
{
    unsigned int result;

    while((VADC_G4RES1 & (1 << VF)) == 0);          // Wait until New Result Available

    result = (VADC_G4RES1 & ((0xFFFF) << RESULT));  // Read Result

    return result;
}

void unlock_Safety_Critical_Reg(void)
{
    /* Password Access to unlock WDTSCON0 */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    /* Modify Access to clear ENDINIT bit */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~ (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);
}

void lock_Safety_Critical_Reg(void)
{
    /* Password Access to unlock WDTSCON0 */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    /* Modify Access to clear ENDINIT bit */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);
}

