/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

// FOR LED
#define PORT10_BASE     (0xF003B000)
#define PORT10_IOCR0    (*(volatile unsigned int*)(PORT10_BASE + 0x10))     /* PORT10_IOCR0의 주소를 이용한 주소의 내용 (변수 아님) */
#define PORT10_OMR      (*(volatile unsigned int*)(PORT10_BASE + 0x04))     /* PORT10_OMR의 주소를 이용한 주소의 내용 (변수 아님)   */
/* volatile 타입으로 선언하는 이유는 동일한 메모리에 1/0을 반복적으로 쓰기를 하므로 컴파일러가 동일한 동작을 무의미하게 반복한다고 판단하여 '최적화'를 실행할 수 있으므로 이를 방지하기 위하여 'volatile' 형으로 선언함 */

#define P10_R0_PC1             11
#define P10_R0_PC2             19
#define P10_R0_PCL1            17
#define P10_R0_PCL2            18
#define P10_R0_PS1             1
#define P10_R0_PS2             2

// FOR RGB LED control
#define PORT02_BASE     (0xF003A200)
#define PORT10_IOCR4    (*(volatile unsigned int*)(PORT10_BASE + 0x14))
#define PORT02_IOCR4    (*(volatile unsigned int*)(PORT02_BASE + 0x14))
#define PORT02_OMR      (*(volatile unsigned int*)(PORT02_BASE + 0x04))
/* volatile 타입으로 선언하는 이유는 동일한 메모리에 1/0을 반복적으로 쓰기를 하므로 컴파일러가 동일한 동작을 무의미하게 반복한다고 판단하여 '최적화'를 실행할 수 있으므로 이를 방지하기 위하여 'volatile' 형으로 선언함 */

#define P10_R0_PC3             27
#define P10_R4_PC5             11
#define P02_R4_PC7             27
#define P10_R0_PCL3            19
#define P10_R4_PCL5            21
#define P02_R4_PCL7            23
#define P10_R0_PS3             3
#define P10_R4_PS5             5
#define P02_R4_PS7             7

// FOR SWITCH
#define PORT02_IOCR0    (*(volatile unsigned int*)(PORT02_BASE + 0x10))
#define PORT02_IN       (*(volatile unsigned int*)(PORT02_BASE + 0x24))

#define P02_R0_PC0             3
#define P02_R0_PC1             11
#define P0                     0
#define P1                     1

// Port/OMR/PC/PCL/PS 설정하는 방법
// 1. 매뉴얼에서 GPIO의 BASE ADDRESS를 찾아서 확인한다.
//


IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* Initialize LED (RED & BLUE) */
void init_LED(void){
    /* reset PC1 & PC2 in IOCR0 */
    PORT10_IOCR0 &= ~((0x1F) << P10_R0_PC1);
    PORT10_IOCR0 &= ~((0x1F) << P10_R0_PC2);

    /* set PC1 & PC2 with push-pull (2b10000) */
    PORT10_IOCR0 |= ((0x10) << P10_R0_PC1);
    PORT10_IOCR0 |= ((0x10) << P10_R0_PC2);
}

void init_RGB(void){
    /* reset PC3 in IOCR0, PC5,PC7 in IOCR4 */
    PORT10_IOCR0 &= ~((0x1F) << P10_R0_PC3);
    PORT10_IOCR4 &= ~((0x1F) << P10_R4_PC5);
    PORT02_IOCR4 &= ~((0x1F) << P02_R4_PC7);

    /* set PC3 in IOCR0, 5, 7 in IOCR4 with push-pull (2b10000) */
    PORT10_IOCR0 |= ((0x10) << P10_R0_PC3);
    PORT10_IOCR4 |= ((0x10) << P10_R4_PC5);
    PORT02_IOCR4 |= ((0x10) << P02_R4_PC7);
}


void init_Switch(void){
    // reset PC0, PC1 in IOCR0
    PORT02_IOCR0 &= ~((0X1F) << P02_R0_PC0);
    PORT02_IOCR0 &= ~((0X1F) << P02_R0_PC1);
    // set PC0, PC1 with push-pull(2b0xx10)
    PORT02_IOCR0 |= ((0x2) << P02_R0_PC0);
    PORT02_IOCR0 |= ((0x2) << P02_R0_PC1);
}

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    volatile int cycle;

    init_LED();
    init_Switch();

    while(1)
    {
        if((PORT02_IN & (1<<P1)) == 0) // 스위치 출렀을 때 low (스위치가 pull up 방식이어서...) 가되고  켜짐
        {
            PORT10_OMR |= (1<<P10_R0_PS1);
        }
        else
        {
            PORT10_OMR |= (1<<P10_R0_PCL1);
        }

        if((PORT02_IN & (1<<P0)) == 0)
        {
            PORT10_OMR |= (1<<P10_R0_PS2);
        }
        else
        {
            PORT10_OMR |= (1<<P10_R0_PCL2);
        }
    }

/*
    init_RGB();

    while(1)
    {
        PORT10_OMR |= ((1<<P10_R0_PCL3)|(1<<P10_R0_PS3));
            for(cycle = 0; cycle < 5000000; cycle++);
        PORT10_OMR |= ((1<<P10_R4_PCL5)|(1<<P10_R4_PS5));
            for(cycle = 0; cycle < 5000000; cycle++);
        PORT02_OMR |= ((1<<P02_R4_PCL7)|(1<<P02_R4_PS7));
            for(cycle = 0; cycle < 5000000; cycle++);
    }
*/
/*
    init_LED();

    while(1)
    {
        PORT10_OMR |= ((1<<P10_R0_PCL1)|(1<<P10_R0_PS1));                 // toggle LED red
            for(cycle = 0; cycle < 5000000; cycle++);       // delay
        PORT10_OMR |= ((1<<P10_R0_PCL2)|(1<<P10_R0_PS2));                 // toggle LED blue
            for(cycle = 0; cycle < 5000000; cycle++);       // delay
    }
*/

    return (1);
}
